version: '3.8'
services:
  mysql_ssl:
    image: mysql/mysql-server:8.0
    container_name: mysql_ssl
    command: [ "mysqld",
               "--character-set-server=utf8mb4",
               "--collation-server=utf8mb4_unicode_ci",
               "--bind-address=0.0.0.0",
               "--require_secure_transport=ON",
               "--ssl-ca=/etc/certs/root-ca.pem",
               "--ssl-cert=/etc/certs/server-cert.pem",
               "--ssl-key=/etc/certs/server-key.pem",
               "--default_authentication_plugin=mysql_native_password" ]
    ports:
      - "42205:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "r00tr00t"
      MYSQL_ROOT_HOST: "%"
